version: '3.3'
services:
  cueo-backend:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      API_URL: ${API_URL}
      ALERT_API_URL: ${ALERT_API_URL}
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      IS_AUTHENTICATION_REQUIRED: ${IS_AUTHENTICATION_REQUIRED}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      REDIS_BROKER_URL: ${REDIS_BROKER_URL}
      DETECTION_SERVICE_PLATFORM: ${DETECTION_SERVICE_PLATFORM}
      AWS_LAMBDA_URL: ${AWS_LAMBDA_URL}
    volumes:
      - sqliteDB:/code/db:rw
      - djangoStaticFiles:/home/staticfiles:rw
  cueo-alerts:
    build:
      context: alerts-api
      dockerfile: Dockerfile

  cueo-frontend:
    build:
      context: ui
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - cueo-backend
    command:
      bash -c "./etc/nginx/conf.d/nginx-entrypoint.sh && nginx -g 'daemon off;'"
    ports:
      - "3000:3000"
    links:
      - "cueo-alerts"
      - "cueo-backend"
      - "cueo-redis"
    volumes:
      - djangoStaticFiles:/home/staticfiles:rw
      
  cueo-redis:
    image: redis

volumes:
  sqliteDB:
  djangoStaticFiles:


    